### PR TITLE
Fix identifiers to asciidoctor rather than asciidoc

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks @jponge!

**Comment by mojavelinux** [comment]
Actually, we seem to need to sync what is released on RubyGems with this repository. That gem is actually coming from a fork. That reminds me to follow up on that merge.

**Comment by mojavelinux** [comment]
@teddy-ma we need to get these two repositories synchronized so that we aren't confusing users. If I rename this repo, will you send a pull request that brings in your changes?

**Comment by teddy-ma** [comment]
@mojavelinux :ok_hand:

**Pull request merged**
